apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql57
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: "/mnt/data/mysql57"  # 원하는 경로 설정
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql57
  labels:
    app: mysql57
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
  volumeName: mysql57
