kind: Service
apiVersion: v1
metadata:
  name: scdf-server
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
  type: NodePort  # LoadBalancer에서 NodePort로 변경
  ports:
    - port: 80
      targetPort: 9393
      name: scdf-server
  selector:
    app: scdf-server