apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-orders-pvc

spec:
  storageClassName: mysql-storage # This should match the storageClassName in mysql-orders-pv.yaml
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi