apiVersion: v1
kind: Service

metadata:
  name: mysql-commerce-service

spec:
  type: ClusterIP
  selector:
    app: mysql-commerce
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
#      nodePort: 30000