apiVersion: v1
kind: Service

metadata:
  name: mysql-orders-service

spec:
  type: NodePort
  selector:
    app: mysql-orders
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000