apiVersion: v1
kind: PersistentVolume

metadata:
  name: mysql-orders-pv

spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
