apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-commerce-pvc

spec:
  storageClassName: mysql-commerce-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi